services:
  authforge:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5255:8080"
      - "7217:7217"
    environment:
      DOTNET_RUNNING_IN_CONTAINER: "true"
      AUTHFORGE__JWT__SECRET: "zwSztOJk211SbIzSBQi6ygvaDVMitb9xAKVyP2x6XelKKimte1EFFvooxG8Rjvre"
      AUTHFORGE__JWT__ISSUER: "AuthForge"
      AUTHFORGE__JWT__AUDIENCE: "AuthForgeUsers"
    volumes:
      - authforge-data:/app/data
    restart: unless-stopped

volumes:
  authforge-data: